services:
  billings:
    build:
      context: .
      dockerfile: ./apps/billings/Dockerfile
      target: development
    command: npm run start:dev bookings
    env_file:
      - ./apps/bookings/.env
    ports:
      - '3000:3000'
    volumes:
      - .:usr/src/app
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
     - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
